<?php

/**
 * Implements hook_form_alter().
 */
function kendra_home_mods_form_user_login_alter(&$form, &$form_state) {
  $form['actions']['password_link'] = array(
    '#markup' => l(t('Forgot your password?'), 'user/password'),
    '#weight' => 999,
  );
}





/**
 * Implements hook_field_widget_form_alter().
 */
function kendra_home_mods_field_widget_form_alter(&$element, &$form_state, $context) {
  // Check we are on the field_user_name.
  if ($element['#field_name'] == 'field_user_name') {
    // Check we are on the registration form
    if ($form_state['build_info']['form_id'] == 'user_register_form') {
      if (isset($element['machine'])) {
        // Hide the machine name.
        $element['machine']['#disabled']  = TRUE;
        // Hide the label.
        $element['machine']['#machine_name']['label'] ='';
      }
    }
  }
}


function kendra_home_mods_pathauto_alias_alter(&$alias, array &$context) {
  //dpm($alias);
  //dpm($context);

  if ($context['module'] == 'user' &&
    !empty($context['data']['user']->field_user_name['und'][0]['machine'])) {
    $alias = 'users/' . $context['data']['user']->field_user_name['und'][0]['machine'];
  }
}



